name: WG-Easy
slug: wg_easy
version: "0.2.3"
description: Simple WireGuard VPN manager with Web UI (WG-Easy)
url: https://github.com/cgfm/WG-Easy-AddOn
arch:
  - aarch64
  - amd64
  - armv7
startup: services
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_MODULE
devices:
  - /dev/net/tun
map:
  - data:rw

# Ingress/Sidebar
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:vpn
panel_title: WG-Easy

# Store visuals
icon: wireguard.png
logo: wireguard.png

options:
  wg_host: ""
  username: "admin"
  password: ""
  wg_port: 51820
  allowed_ips: "0.0.0.0/0, ::/0"
  default_dns: "1.1.1.1, 1.0.0.1"

schema:
  wg_host: str
  username: str
  password: str?
  wg_port: int
  allowed_ips: str
  default_dns: str
